# DEV Dockerfile (hot reload)
FROM node:20-alpine

WORKDIR /app

# package files
COPY package*.json ./

# install deps
RUN npm install

# copy source
COPY . .

# Vite dev port
EXPOSE 5173

# run vite dev server
CMD ["npm", "run", "dev", "--", "--host"]
